export const songs = [
  "Vices - $uicideboy$",
  "Blinding Lights - The Weeknd",
  "Shape of You - Ed Sheeran",
  "Dance Monkey - Tones and I",
  "Someone You Loved - Lewis Capaldi",
  "Sunflower - Post Malone & Swae Lee",
  "Stay - The Kid LAROI & Justin Bieber",
  "Drivers License - Olivia Rodrigo",
  "Good 4 U - Olivia Rodrigo",
  "Levitating - Dua Lipa",
  "Peaches - Justin Bieber",
  "Bad Habits - Ed Sheeran",
  "Industry Baby - Lil Nas X & Jack Harlow",
  "Montero (Call Me By Your Name) - Lil Nas X",
  "Watermelon Sugar - Harry Styles",
  "As It Was - Harry Styles",
  "Save Your Tears - The Weeknd",
  "Positions - Ariana Grande",
  "Stupid - Ashnikko ft. Yung Baby Tate",
  "ROXANNE - Arizona Zervas",
  "Mood - 24kGoldn ft. iann dior",
  "Therefore I Am - Billie Eilish",
  "Lovely - Billie Eilish & Khalid",
  "Bad Guy - Billie Eilish",
  "No Time To Die - Billie Eilish",
  "Circles - Post Malone",
  "Goosebumps - Travis Scott",
  "SICKO MODE - Travis Scott",
  "Rockstar - DaBaby ft. Roddy Ricch",
  "Lucid Dreams - Juice WRLD",
  "All Girls Are the Same - Juice WRLD",
  "Old Town Road - Lil Nas X",
  "Panini - Lil Nas X",
  "Without Me - Halsey",
  "Eastside - Benny Blanco, Halsey & Khalid",
  "Happier - Marshmello & Bastille",
  "Friends - Marshmello & Anne-Marie",
  "Silence - Marshmello ft. Khalid",
  "Closer - The Chainsmokers & Halsey",
  "Something Just Like This - The Chainsmokers & Coldplay",
  "Don't Start Now - Dua Lipa",
  "New Rules - Dua Lipa",
  "IDGAF - Dua Lipa",
  "One Kiss - Calvin Harris & Dua Lipa",
  "Titanium - David Guetta ft. Sia",
  "Cheap Thrills - Sia",
  "Chandelier - Sia",
  "Unstoppable - Sia",
  "Say So - Doja Cat",
  "Kiss Me More - Doja Cat ft. SZA",
  "Woman - Doja Cat",
  "Need to Know - Doja Cat",
  "Starboy - The Weeknd ft. Daft Punk",
  "Can't Feel My Face - The Weeknd",
  "Earned It - The Weeknd",
  "In The Night - The Weeknd",
  "God's Plan - Drake",
  "In My Feelings - Drake",
  "Hotline Bling - Drake",
  "One Dance - Drake ft. Wizkid & Kyla",
  "Laugh Now Cry Later - Drake ft. Lil Durk",
  "Nonstop - Drake",
  "Nice for What - Drake",
  "Life Goes On - BTS",
  "Dynamite - BTS",
  "Butter - BTS",
  "Permission to Dance - BTS",
  "Boy With Luv - BTS ft. Halsey",
  "Kill This Love - BLACKPINK",
  "How You Like That - BLACKPINK",
  "DDU-DU DDU-DU - BLACKPINK",
  "Ice Cream - BLACKPINK & Selena Gomez",
  "Señorita - Shawn Mendes & Camila Cabello",
  "Stitches - Shawn Mendes",
  "There's Nothing Holdin' Me Back - Shawn Mendes",
  "Havana - Camila Cabello ft. Young Thug",
  "Never Be the Same - Camila Cabello",
  "Memories - Maroon 5",
  "Girls Like You - Maroon 5 ft. Cardi B",
  "Sugar - Maroon 5",
  "Animals - Maroon 5",
  "Believer - Imagine Dragons",
  "Thunder - Imagine Dragons",
  "Demons - Imagine Dragons",
  "Radioactive - Imagine Dragons",
  "Whatever It Takes - Imagine Dragons",
  "Counting Stars - OneRepublic",
  "Apologize - OneRepublic",
  "Love Me Like You Do - Ellie Goulding",
  "Burn - Ellie Goulding",
  "On My Mind - Ellie Goulding",
  "Photograph - Ed Sheeran",
  "Thinking Out Loud - Ed Sheeran",
  "Perfect - Ed Sheeran",
  "Shivers - Ed Sheeran",
  "Castle on the Hill - Ed Sheeran",
  "7 Rings - Ariana Grande",
  "Into You - Ariana Grande",
  "Thank U, Next - Ariana Grande",
  "Side to Side - Ariana Grande ft. Nicki Minaj",
  "No Tears Left to Cry - Ariana Grande",
];
